CREATE TABLE "TREEINFO" (
	"TREENAME"	VARCHAR2(100)		NULL,
	"TREELIFE"	VARCHAR2(5)		NULL,
	"TREEPOINT"	VARCHAR2(1000)		NULL,
	"TREEPHOTO"	VARCHAR2(1000)		NULL
);
CREATE TABLE "USERINFO" (
	"USERID"	VARCHAR2(50)		NOT NULL,
	"USERPW"	VARCHAR2(30)		NULL,
	"USERNAME"	VARCHAR2(20)		NULL,
	"USERGENDER"	VARCHAR2(1)		NULL,
	"NICKNAME"	VARCHAR2(30)		NULL
);

CREATE TABLE "TREECORPORATION" (
	"CPNAME"	VARCHAR2(20)		NOT NULL,
	"CPURL"	VARCHAR2(500)		NULL,
	"CPINTRO"	VARCHAR2(2000)		NULL,
	"CPPHOTO"	VARCHAR2(1000)		NULL,
	"CPCALL"	VARCHAR2(15)		NULL
);
CREATE TABLE "TREECAMPAIN" (
	"TCCODE"	NUMBER(3)		NOT NULL,
	"CPNAME"	VARCHAR2(50)		NOT NULL,
	"TCINTRO"	VARCHAR2(2000)		NULL,
	"TCURL"	VARCHAR2(500)		NULL,
	"TCCALL"	VARCHAR2(15)		NULL
);
ALTER TABLE "TREEINFO" ADD CONSTRAINT "PK_TREEINFO" PRIMARY KEY (
	"TREENAME"
);

ALTER TABLE "USERINFO" ADD CONSTRAINT "PK_USERINFO" PRIMARY KEY (
	"USERID"
);

ALTER TABLE "TREECORPORATION" ADD CONSTRAINT "PK_TREECORPORATION" PRIMARY KEY (
	"CPNAME"
);

ALTER TABLE "TREECAMPAIN" ADD CONSTRAINT "PK_TREECAMPAIN" PRIMARY KEY (
	"TCCODE",
	"CPNAME"
);

ALTER TABLE "TREECAMPAIN" ADD CONSTRAINT "FK_TP_TO_TC" FOREIGN KEY (
	"CPNAME"
)
REFERENCES "TREECORPORATION" (
	"CPNAME"
);
/*TREEINFO 가값*/
INSERT INTO TREEINFO VALUES('오민우나무','100','학생이다.','오민우.JPG');
INSERT INTO TREEINFO VALUES('서준호나무','90','학생이다.','서준호.JPG');

/*USERINFO 가값*/
INSERT INTO USERINFO VALUES('abc123','1234','오민우','M','닝겐군단');
INSERT INTO USERINFO VALUES('ZZ','1','서준호','F','SLDRPSRNSEKS');

/*TREECORPORATION 가값*/
INSERT INTO TREECORPORATION VALUES('트리플래닛','https://treepla.net/','나무심는 기업','트리플래닛.JPG','02-512-2492');

/*TREECAMPAIN 가값*/
INSERT INTO TREECAMPAIN VALUES('001','트리플래닛','강원도 산불 피해하는 거','https://treepla.net/forestfires','02-512-2492');