CREATE TABLE "TREEINFO" (
	"TREENAME"	VARCHAR2(100)		NULL,
	"TREELIFE"	VARCHAR2(5)		NULL,
	"TREEPOINT"	VARCHAR2(1000)		NULL,
	"TREEPHOTO"	VARCHAR2(1000)		NULL
);
CREATE TABLE "USERINFO" (
	"USERID"	VARCHAR2(50)		NOT NULL,
	"USERPW"	VARCHAR2(30)		NULL,
	"USERNAME"	VARCHAR2(20)		NULL,
	"USERGENDER"	VARCHAR2(1)		NULL,
	"NICKNAME"	VARCHAR2(30)		NULL
);
CREATE TABLE "TREECORPORATION" (
	"CPNAME"	VARCHAR2(20)		NOT NULL,
	/*CPURL 포링키로 참조해야함. erd 다시짜*/
	"CPURL"	VARCHAR2(500)		NULL,
	"CPINTRO"	VARCHAR2(2000)		NULL,
	"CPPHOTO"	VARCHAR2(1000)		NULL,
	"CPCALL"	VARCHAR2(15)		NULL
);
CREATE TABLE "TREECAMPAIN" (
	"TCCODE"	NUMBER(3)		NOT NULL,
	"TCSTATE"	NUMBER(1)		NOT NULL,
	"CPNAME"	VARCHAR2(50)		NOT NULL,
	"TCNAME"	VARCHAR2(50)		NOT NULL,
	"TCINTRO"	VARCHAR2(2000)		NULL,
	"TCURL"	VARCHAR2(500)		NULL,
	"TCCALL"	VARCHAR2(15)		NULL
);
ALTER TABLE "TREEINFO" ADD CONSTRAINT "PK_TREEINFO" PRIMARY KEY (
	"TREENAME"
);

ALTER TABLE "USERINFO" ADD CONSTRAINT "PK_USERINFO" PRIMARY KEY (
	"USERID"
);

ALTER TABLE "TREECORPORATION" ADD CONSTRAINT "PK_TREECORPORATION" PRIMARY KEY (
	"CPNAME"
);

ALTER TABLE "TREECAMPAIN" ADD CONSTRAINT "PK_TREECAMPAIN" PRIMARY KEY (
	"TCCODE",
	"CPNAME"
);

ALTER TABLE "TREECAMPAIN" ADD CONSTRAINT "FK_TP_TO_TC" FOREIGN KEY (
	"CPNAME"
)
REFERENCES "TREECORPORATION" (
	"CPNAME"
);
/*TREEINFO 가값*/
INSERT INTO TREEINFO VALUES('오민우나무','100','학생이다.','오민우.JPG');
INSERT INTO TREEINFO VALUES('서준호나무','90','학생이다.','서준호.JPG');

/*USERINFO 가값*/
INSERT INTO USERINFO VALUES('abc123','1234','오민우','M','닝겐군단');
INSERT INTO USERINFO VALUES('ZZ','1','서준호','F','SLDRPSRNSEKS');

/*TREECORPORATION 가값*/
INSERT INTO TREECORPORATION VALUES('트리플래닛','https://treepla.net/','나무심는 기업','트리플래닛.JPG','02-512-2492');

/*TREECAMPAIN 가값*/
INSERT INTO TREECAMPAIN VALUES('001', 1 ,'트리플래닛', '강원 산불피해 복구 숲', '까맣게 타버린 강원의 숲, 까맣게 잊은 당신에게','https://treepla.net/forestfires','02-512-2492');

insert into treecorporation values('환경교육센터','http://www.edutopia.or.kr/node/2200','환경교육센터는 생명, 평화, 참여, 나눔의 가치를 추구합니다.','11','02-735-8677');
insert into treecampain values(002,1, '환경교육센터','생명의 숲', '생명의숲은 시민의 힘으로 건강한 숲, 지속가능한 사회를 만드는 NGO입니다.','https://booking.naver.com/booking/12/bizes/436992/items/3955687','02-735-3232');
